export const QUESTIONS_GUIA_I = [
  { id: 1, text: "¿Ha presenciado o sufrido alguna vez, durante o con motivo del trabajo un acontecimiento como los siguientes: accidente que tenga como consecuencia la muerte, la pérdida de un miembro o una lesión grave?" },
  { id: 2, text: "¿Asaltos?" },
  { id: 3, text: "¿Actos violentos que derivaron en lesiones graves?" },
  { id: 4, text: "¿Secuestro?" },
  { id: 5, text: "¿Amenazas de muerte?" },
  { id: 6, text: "¿Cualquier otro que ponga en riesgo su vida o salud, y/o la de otras personas?" },
  { id: 7, text: "¿Ha tenido recuerdos recurrentes sobre el acontecimiento que le provocan malestares?" },
  { id: 8, text: "¿Ha tenido sueños de carácter recurrente sobre el acontecimiento, que le producen malestar?" },
  { id: 9, text: "¿Se ha esforzado por evitar tener pensamientos, recuerdos o sentimientos sobre el acontecimiento?" },
  { id: 10, text: "¿Se ha esforzado por evitar personas, lugares, actividades u objetos que le traen recuerdos del acontecimiento?" },
  { id: 11, text: "¿Ha tenido dificultad para recordar alguna parte importante del evento?" },
  { id: 12, text: "¿Ha disminuido su interés en sus actividades cotidianas?" },
  { id: 13, text: "¿Se ha sentido usted alejado o distante de los demás?" },
  { id: 14, text: "¿Ha notado que tiene dificultad para expresar sus sentimientos?" },
  { id: 15, text: "¿Ha tenido la impresión de que su vida se va a acortar, que va a morir joven o que no va a hacer una familia o lograr metas en el futuro?" },
  { id: 16, text: "¿Ha tenido usted dificultades para quedarse dormido o para seguir durmiendo?" },
  { id: 17, text: "¿Ha estado particularmente irritable o ha tenido arranques de enojo?" },
  { id: 18, text: "¿Ha tenido dificultad para concentrarse?" },
  { id: 19, text: "¿Ha estado particularmente nervioso o ha estado en constante alerta?" },
  { id: 20, text: "¿Se ha sobresaltado fácilmente por cualquier cosa?" }
];

export const QUESTIONS_GUIA_II = [
  { id: 1, text: "El espacio donde trabajo me permite realizar mis actividades de manera segura e higiénica" },
  { id: 2, text: "Mi trabajo me exige hacer mucho esfuerzo físico" },
  { id: 3, text: "Me preocupa sufrir un accidente en mi trabajo" },
  { id: 4, text: "Considero que las actividades que realizo son peligrosas" },
  { id: 5, text: "Por la cantidad de trabajo que tengo debo quedarme tiempo adicional a mi turno" },
  { id: 6, text: "Por la cantidad de trabajo que tengo debo trabajar sin parar" },
  { id: 7, text: "Considero que es necesario mantener un ritmo de trabajo acelerado" },
  { id: 8, text: "Mi trabajo exige que esté muy concentrado" },
  { id: 9, text: "Mi trabajo requiere que memorice mucha información" },
  { id: 10, text: "En mi trabajo tengo que tomar decisiones difíciles muy rápido" },
  { id: 11, text: "Mi trabajo exige que atienda varios asuntos al mismo tiempo" },
  { id: 12, text: "En mi trabajo soy responsable de cosas de mucho valor" },
  { id: 13, text: "Respondo ante mi jefe por los resultados de toda mi área de trabajo" },
  { id: 14, text: "En el trabajo me dan órdenes contradictorias" },
  { id: 15, text: "Considero que en mi trabajo me piden hacer cosas innecesarias" },
  { id: 16, text: "Trabajo horas extras más de tres veces a la semana" },
  { id: 17, text: "Mi trabajo me exige laborar en días de descanso, festivos o fines de semana" },
  { id: 18, text: "Considero que el tiempo en el trabajo absorbe mucho de mi tiempo libre" },
  { id: 19, text: "El tiempo que paso en el trabajo afecta mis responsabilidades familiares" },
  { id: 20, text: "Pienso en las actividades del trabajo cuando estoy en mi tiempo libre" },
  { id: 21, text: "Mi jefe permite que organice mi tiempo de trabajo" },
  { id: 22, text: "Mi jefe me permite decidir cómo realizo el trabajo" },
  { id: 23, text: "Las decisiones que tomo en el trabajo son respetadas" },
  { id: 24, text: "En mi trabajo puedo proponer mejoras para mis actividades" },
  { id: 25, text: "En mi trabajo puedo tomar pausas cuando las necesito" },
  { id: 26, text: "El trabajo me permite desarrollar mis habilidades" },
  { id: 27, text: "Mi jefe me informa sobre las decisiones que toma" },
  { id: 28, text: "Mi jefe reconoce mi esfuerzo" },
  { id: 29, text: "Mi jefe toma en cuenta mis ideas y opiniones" },
  { id: 30, text: "Mi jefe me comunica los cambios que ocurren en mi lugar de trabajo" },
  { id: 31, text: "Recibo la capacitación necesaria para hacer bien mi trabajo" },
  { id: 32, text: "La capacitación que recibo es útil para mi trabajo" },
  { id: 33, text: "Mis compañeros me ayudan cuando tengo mucho trabajo" },
  { id: 34, text: "Mis compañeros de trabajo escuchan y toman en cuenta mis opiniones" },
  { id: 35, text: "Existe compañerismo entre el personal" },
  { id: 36, text: "El trato con mis compañeros de trabajo es respetuoso" },
  { id: 37, text: "Mi jefe me trata de forma respetuosa" },
  { id: 38, text: "En mi trabajo hay violencia (golpes, empujones, etc.)" },
  { id: 39, text: "En mi trabajo hay faltas de respeto (insultos, burlas, etc.)" },
  { id: 40, text: "En mi trabajo hay personas que se burlan de mí" },
  { id: 41, text: "Atiendo a clientes o usuarios muy enojados" },
  { id: 42, text: "Mi trabajo me exige atender a personas muy necesitadas de ayuda o enfermas" },
  { id: 43, text: "Para hacer mi trabajo debo demostrar sentimientos distintos a los míos" },
  { id: 44, text: "Mis trabajadores comunican tarde los asuntos de trabajo" },
  { id: 45, text: "Mis trabajadores dificultan el logro de los resultados del trabajo" },
  { id: 46, text: "Mis trabajadores ignoran las sugerencias para mejorar su trabajo" }
];

export const QUESTIONS_GUIA_III = [
  { id: 1, text: "El espacio donde trabajo me permite realizar mis actividades de manera segura e higiénica" },
  { id: 2, text: "Mi trabajo me exige hacer mucho esfuerzo físico" },
  { id: 3, text: "Me preocupa sufrir un accidente en mi trabajo" },
  { id: 4, text: "Considero que las actividades que realizo son peligrosas" },
  { id: 5, text: "Considero que en mi trabajo se aplican las normas de seguridad y salud en el trabajo" },
  { id: 6, text: "Por la cantidad de trabajo que tengo debo quedarme tiempo adicional a mi turno" },
  { id: 7, text: "Por la cantidad de trabajo que tengo debo trabajar sin parar" },
  { id: 8, text: "Considero que es necesario mantener un ritmo de trabajo acelerado" },
  { id: 9, text: "Mi trabajo exige que esté muy concentrado" },
  { id: 10, text: "Mi trabajo requiere que memorice mucha información" },
  { id: 11, text: "En mi trabajo tengo que tomar decisiones difíciles muy rápido" },
  { id: 12, text: "Mi trabajo exige que atienda varios asuntos al mismo tiempo" },
  { id: 13, text: "En mi trabajo soy responsable de cosas de mucho valor" },
  { id: 14, text: "Respondo ante mi jefe por los resultados de toda mi área de trabajo" },
  { id: 15, text: "En el trabajo me dan órdenes contradictorias" },
  { id: 16, text: "Considero que en mi trabajo me piden hacer cosas innecesarias" },
  { id: 17, text: "Trabajo horas extras más de tres veces a la semana" },
  { id: 18, text: "Mi trabajo me exige laborar en días de descanso, festivos o fines de semana" },
  { id: 19, text: "Considero que el tiempo en el trabajo absorbe mucho de mi tiempo libre" },
  { id: 20, text: "El tiempo que paso en el trabajo afecta mis responsabilidades familiares" },
  { id: 21, text: "Pienso en las actividades del trabajo cuando estoy en mi tiempo libre" },
  { id: 22, text: "Mis responsabilidades familiares afectan mi trabajo" },
  { id: 23, text: "Mi jefe permite que organice mi tiempo de trabajo" },
  { id: 24, text: "Mi jefe me permite decidir cómo realizo el trabajo" },
  { id: 25, text: "Las decisiones que tomo en el trabajo son respetadas" },
  { id: 26, text: "En mi trabajo puedo proponer mejoras para mis actividades" },
  { id: 27, text: "En mi trabajo puedo tomar pausas cuando las necesito" },
  { id: 28, text: "El trabajo me permite desarrollar mis habilidades" },
  { id: 29, text: "Mi jefe me informa sobre las decisiones que toma" },
  { id: 30, text: "Mi jefe reconoce mi esfuerzo" },
  { id: 31, text: "Mi jefe toma en cuenta mis ideas y opiniones" },
  { id: 32, text: "Mi jefe me comunica los cambios que ocurren en mi lugar de trabajo" },
  { id: 33, text: "Recibo la capacitación necesaria para hacer bien mi trabajo" },
  { id: 34, text: "La capacitación que recibo es útil para mi trabajo" },
  { id: 35, text: "Mi jefe me da instrucciones claras de lo que espera de mi trabajo" },
  { id: 36, text: "En mi trabajo me informan sobre los resultados que espera de mí" },
  { id: 37, text: "Existe compañerismo entre el personal" },
  { id: 38, text: "El trato con mis compañeros de trabajo es respetuoso" },
  { id: 39, text: "Mi jefe me trata de forma respetuosa" },
  { id: 40, text: "Mis compañeros me ayudan cuando tengo mucho trabajo" },
  { id: 41, text: "Mis compañeros de trabajo escuchan y toman en cuenta mis opiniones" },
  { id: 42, text: "La comunicación entre mis compañeros y yo es buena" },
  { id: 43, text: "La información que recibo sobre mi trabajo es clara" },
  { id: 44, text: "Me informan a quién debo dirigirme para resolver problemas" },
  { id: 45, text: "Me explican claramente los resultados que se esperan de mi trabajo" },
  { id: 46, text: "Me informan sobre lo que hago bien y lo que debo mejorar" },
  { id: 47, text: "Me comunican a tiempo los cambios que afectan mi trabajo" },
  { id: 48, text: "En mi trabajo puedo expresarme libremente" },
  { id: 49, text: "Las evaluaciones de mi desempeño son justas" },
  { id: 50, text: "Recibo un trato justo y equitativo" },
  { id: 51, text: "La distribución del trabajo es justa y equitativa" },
  { id: 52, text: "En mi trabajo se fomenta el trabajo en equipo" },
  { id: 53, text: "La empresa se preocupa por mi bienestar" },
  { id: 54, text: "Siento orgullo de trabajar para esta empresa" },
  { id: 55, text: "Me siento comprometido(a) con la empresa" },
  { id: 56, text: "En mi trabajo recibo el apoyo que necesito para realizar mis tareas" },
  { id: 57, text: "En mi trabajo hay violencia (golpes, empujones, etc.)" },
  { id: 58, text: "En mi trabajo hay faltas de respeto (insultos, burlas, etc.)" },
  { id: 59, text: "En mi trabajo hay personas que se burlan de mí" },
  { id: 60, text: "En mi trabajo he sido ignorado(a) o excluido(a) por mis compañeros o jefe" },
  { id: 61, text: "En mi trabajo me hacen sentir menos o se burlan de mis logros" },
  { id: 62, text: "En mi trabajo me han amenazado" },
  { id: 63, text: "En mi trabajo hay personas que se la pasan criticando mis labores" },
  { id: 64, text: "En mi trabajo he recibido burlas o insultos frente a mis compañeros" },
  { id: 65, text: "Atiendo a clientes o usuarios muy enojados" },
  { id: 66, text: "Mi trabajo me exige atender a personas muy necesitadas de ayuda o enfermas" },
  { id: 67, text: "Para hacer mi trabajo debo demostrar sentimientos distintos a los míos" },
  { id: 68, text: "Mi trabajo me exige atender situaciones de violencia" },
  { id: 69, text: "Mis trabajadores comunican tarde los asuntos de trabajo" },
  { id: 70, text: "Mis trabajadores dificultan el logro de los resultados del trabajo" },
  { id: 71, text: "Mis trabajadores cooperan poco cuando se necesita" },
  { id: 72, text: "Mis trabajadores ignoran las sugerencias para mejorar su trabajo" }
];
