export const QUESTIONS_GUIA_I = [
  { id: 1, text: "¿Ha presenciado o sufrido alguna vez, durante o con motivo del trabajo un acontecimiento como los siguientes: accidente que tenga como consecuencia la muerte, la pérdida de un miembro o una lesión grave?" },
  { id: 2, text: "¿Asaltos?" },
  { id: 3, text: "¿Actos violentos que derivaron en lesiones graves?" },
  { id: 4, text: "¿Secuestro?" },
  { id: 5, text: "¿Amenazas de muerte?" },
  { id: 6, text: "¿Cualquier otro que ponga en riesgo su vida o salud, y/o la de otras personas?" },
  { id: 7, text: "¿Ha tenido recuerdos recurrentes sobre el acontecimiento que le provocan malestares?" },
  { id: 8, text: "¿Ha tenido sueños de carácter recurrente sobre el acontecimiento, que le producen malestar?" },
  { id: 9, text: "¿Se ha esforzado por evitar tener pensamientos, recuerdos o sentimientos sobre el acontecimiento?" },
  { id: 10, text: "¿Se ha esforzado por evitar personas, lugares, actividades u objetos que le traen recuerdos del acontecimiento?" },
  { id: 11, text: "¿Ha tenido dificultad para recordar alguna parte importante del evento?" },
  { id: 12, text: "¿Ha disminuido su interés en sus actividades cotidianas?" },
  { id: 13, text: "¿Se ha sentido usted alejado o distante de los demás?" },
  { id: 14, text: "¿Ha notado que tiene dificultad para expresar sus sentimientos?" },
  { id: 15, text: "¿Ha tenido la impresión de que su vida se va a acortar, que va a morir joven o que no va a hacer una familia o lograr metas en el futuro?" },
  { id: 16, text: "¿Ha tenido usted dificultades para quedarse dormido o para seguir durmiendo?" },
  { id: 17, text: "¿Ha estado particularmente irritable o ha tenido arranques de enojo?" },
  { id: 18, text: "¿Ha tenido dificultad para concentrarse?" },
  { id: 19, text: "¿Ha estado particularmente nervioso o ha estado en constante alerta?" },
  { id: 20, text: "¿Se ha sobresaltado fácilmente por cualquier cosa?" }
];

export const QUESTIONS_GUIA_II = [
  { id: 1, text: "Mi trabajo me exige hacer mucho esfuerzo físico" },
  { id: 2, text: "Me preocupa sufrir un accidente en mi trabajo" },
  { id: 3, text: "Considero que las actividades que realizo son peligrosas" },
  { id: 4, text: "Por la cantidad de trabajo que tengo debo quedarme tiempo adicional a mi turno" },
  { id: 5, text: "Por la cantidad de trabajo que tengo debo trabajar sin parar" },
  { id: 6, text: "Considero que es necesario mantener un ritmo de trabajo acelerado" },
  { id: 7, text: "Mi trabajo exige que esté muy concentrado" },
  { id: 8, text: "Mi trabajo requiere que memorice mucha información" },
  { id: 9, text: "Mi trabajo exige que atienda varios asuntos al mismo tiempo" },
  { id: 10, text: "En mi trabajo soy responsable de cosas de mucho valor" },
  { id: 11, text: "Respondo ante mi jefe por los resultados de toda mi área de trabajo" },
  { id: 12, text: "En mi trabajo me dan órdenes contradictorias" },
  { id: 13, text: "Considero que en mi trabajo me piden hacer cosas innecesarias" },
  { id: 14, text: "Trabajo horas extras más de tres veces a la semana" },
  { id: 15, text: "Mi trabajo me exige laborar en días de descanso, festivos o fines de semana" },
  { id: 16, text: "Considero que el tiempo en el trabajo es mucho y perjudica mis actividades familiares o personales" },
  { id: 17, text: "Pienso en las actividades familiares o personales cuando estoy en mi trabajo" },
  { id: 18, text: "Mi trabajo permite que desarrolle nuevas habilidades" },
  { id: 19, text: "En mi trabajo puedo aspirar a un mejor puesto" },
  { id: 20, text: "Durante mi jornada de trabajo puedo tomar pausas cuando las necesito" },
  { id: 21, text: "Puedo decidir la velocidad a la que realizo mis actividades en mi trabajo" },
  { id: 22, text: "Puedo cambiar el orden de las actividades que realizo en mi trabajo" },
  { id: 23, text: "Me informan con claridad cuáles son mis funciones" },
  { id: 24, text: "Me explican claramente los resultados que debo obtener en mi trabajo" },
  { id: 25, text: "Me informan con quién puedo resolver problemas o asuntos de trabajo" },
  { id: 26, text: "Me permiten asistir a capacitaciones relacionadas con mi trabajo" },
  { id: 27, text: "Recibo capacitación útil para hacer mi trabajo" },
  { id: 28, text: "Mi jefe tiene en cuenta mis puntos de vista y opiniones" },
  { id: 29, text: "Mi jefe ayuda a solucionar los problemas que se presentan en el trabajo" },
  { id: 30, text: "Puedo confiar en mis compañeros de trabajo" },
  { id: 31, text: "Cuando tenemos que realizar trabajo de equipo los compañeros colaboran" },
  { id: 32, text: "Mis compañeros de trabajo me ayudan cuando tengo dificultades" },
  { id: 33, text: "En mi trabajo puedo expresarme libremente sin interrupciones" },
  { id: 34, text: "Recibo críticas constantes a mi persona y/o trabajo" },
  { id: 35, text: "Recibo burlas, calumnias, difamaciones, humillaciones o ridiculizaciones" },
  { id: 36, text: "Se ignora mi presencia o se me excluye de las reuniones de trabajo y en la toma de decisiones" },
  { id: 37, text: "Se manipulan las situaciones de trabajo para hacerme parecer un mal trabajador" },
  { id: 38, text: "Se ignoran mis éxitos laborales y se atribuyen a otros trabajadores" },
  { id: 39, text: "Me bloquean o impiden las oportunidades que tengo para obtener ascenso o mejora en mi trabajo" },
  { id: 40, text: "He presenciado actos de violencia en mi centro de trabajo" },
  { id: 41, text: "Atiendo clientes o usuarios muy enojados" },
  { id: 42, text: "Mi trabajo me exige atender personas muy necesitadas de ayuda o enfermas" },
  { id: 43, text: "Para hacer mi trabajo debo demostrar sentimientos distintos a los míos" },
  { id: 44, text: "Comunican tarde los asuntos de trabajo" },
  { id: 45, text: "Dificultan el logro de los resultados del trabajo" },
  { id: 46, text: "Ignoran las sugerencias para mejorar su trabajo" }
];

export const QUESTIONS_GUIA_III = [
  { id: 1, text: "El espacio donde trabajo me permite realizar mis actividades de manera segura e higiénica" },
  { id: 2, text: "Mi trabajo me exige hacer mucho esfuerzo físico" },
  { id: 3, text: "Me preocupa sufrir un accidente en mi trabajo" },
  { id: 4, text: "Considero que en mi trabajo se aplican las normas de seguridad y salud en el trabajo" },
  { id: 5, text: "Considero que las actividades que realizo son peligrosas" },
  { id: 6, text: "Por la cantidad de trabajo que tengo debo quedarme tiempo adicional a mi turno" },
  { id: 7, text: "Por la cantidad de trabajo que tengo debo trabajar sin parar" },
  { id: 8, text: "Considero que es necesario mantener un ritmo de trabajo acelerado" },
  { id: 9, text: "Mi trabajo exige que esté muy concentrado" },
  { id: 10, text: "Mi trabajo requiere que memorice mucha información" },
  { id: 11, text: "En mi trabajo tengo que tomar decisiones difíciles muy rápido" },
  { id: 12, text: "Mi trabajo exige que atienda varios asuntos al mismo tiempo" },
  { id: 13, text: "En mi trabajo soy responsable de cosas de mucho valor" },
  { id: 14, text: "Respondo ante mi jefe por los resultados de toda mi área de trabajo" },
  { id: 15, text: "En el trabajo me dan órdenes contradictorias" },
  { id: 16, text: "Considero que en mi trabajo me piden hacer cosas innecesarias" },
  { id: 17, text: "Trabajo horas extras más de tres veces a la semana" },
  { id: 18, text: "Mi trabajo me exige laborar en días de descanso, festivos o fines de semana" },
  { id: 19, text: "Considero que el tiempo en el trabajo es mucho y perjudica mis actividades familiares o personales" },
  { id: 20, text: "Debo atender asuntos de trabajo cuando estoy en casa" },
  { id: 21, text: "Pienso en las actividades familiares o personales cuando estoy en mi trabajo" },
  { id: 22, text: "Pienso que mis responsabilidades familiares afectan mi trabajo" },
  { id: 23, text: "Mi trabajo permite que desarrolle nuevas habilidades" },
  { id: 24, text: "En mi trabajo puedo aspirar a un mejor puesto" },
  { id: 25, text: "Durante mi jornada de trabajo puedo tomar pausas cuando las necesito" },
  { id: 26, text: "Puedo decidir cuánto trabajo realizo durante la jornada laboral" },
  { id: 27, text: "Puedo decidir la velocidad a la que realizo mis actividades en mi trabajo" },
  { id: 28, text: "Puedo cambiar el orden de las actividades que realizo en mi trabajo" },
  { id: 29, text: "Los cambios que se presentan en mi trabajo dificultan mi labor" },
  { id: 30, text: "Cuando se presentan cambios en mi trabajo se tienen en cuenta mis ideas o aportaciones" },
  { id: 31, text: "Me informan con claridad cuáles son mis funciones" },
  { id: 32, text: "Me explican claramente los resultados que debo obtener en mi trabajo" },
  { id: 33, text: "Me explican claramente los objetivos de mi trabajo" },
  { id: 34, text: "Me informan con quién puedo resolver problemas o asuntos de trabajo" },
  { id: 35, text: "Me permiten asistir a capacitaciones relacionadas con mi trabajo" },
  { id: 36, text: "Recibo capacitación útil para hacer mi trabajo" },
  { id: 37, text: "Mi jefe ayuda a organizar mejor el trabajo" },
  { id: 38, text: "Mi jefe tiene en cuenta mis puntos de vista y opiniones" },
  { id: 39, text: "Mi jefe me comunica a tiempo la información relacionada con el trabajo" },
  { id: 40, text: "La orientación que me da mi jefe me ayuda a realizar mejor mi trabajo" },
  { id: 41, text: "Mi jefe ayuda a solucionar los problemas que se presentan en el trabajo" },
  { id: 42, text: "Puedo confiar en mis compañeros de trabajo" },
  { id: 43, text: "Entre compañeros solucionamos los problemas de trabajo de forma respetuosa" },
  { id: 44, text: "En mi trabajo me hacen sentir parte del grupo" },
  { id: 45, text: "Cuando tenemos que realizar trabajo de equipo los compañeros colaboran" },
  { id: 46, text: "Mis compañeros de trabajo me ayudan cuando tengo dificultades" },
  { id: 47, text: "Me informan sobre lo que hago bien en mi trabajo" },
  { id: 48, text: "La forma como evalúan mi trabajo en mi centro de trabajo me ayuda a mejorar mi desempeño" },
  { id: 49, text: "En mi centro de trabajo me pagan a tiempo mi salario" },
  { id: 50, text: "El pago que recibo es el que merezco por el trabajo que realizo" },
  { id: 51, text: "Si obtengo los resultados esperados en mi trabajo me recompensan o reconocen" },
  { id: 52, text: "Las personas que hacen bien el trabajo pueden crecer laboralmente" },
  { id: 53, text: "Considero que mi trabajo es estable" },
  { id: 54, text: "En mi trabajo existe continua rotación de personal" },
  { id: 55, text: "Siento orgullo de laborar en este centro de trabajo" },
  { id: 56, text: "Me siento comprometido con mi trabajo" },
  { id: 57, text: "En mi trabajo puedo expresarme libremente sin interrupciones" },
  { id: 58, text: "Recibo críticas constantes a mi persona y/o trabajo" },
  { id: 59, text: "Recibo burlas, calumnias, difamaciones, humillaciones o ridiculizaciones" },
  { id: 60, text: "Se ignora mi presencia o se me excluye de las reuniones de trabajo y en la toma de decisiones" },
  { id: 61, text: "Se manipulan las situaciones de trabajo para hacerme parecer un mal trabajador" },
  { id: 62, text: "Se ignoran mis éxitos laborales y se atribuyen a otros trabajadores" },
  { id: 63, text: "Me bloquean o impiden las oportunidades que tengo para obtener ascenso o mejora en mi trabajo" },
  { id: 64, text: "He presenciado actos de violencia en mi centro de trabajo" },
  { id: 65, text: "Atiendo clientes o usuarios muy enojados" },
  { id: 66, text: "Mi trabajo me exige atender personas muy necesitadas de ayuda o enfermas" },
  { id: 67, text: "Para hacer mi trabajo debo demostrar sentimientos distintos a los míos" },
  { id: 68, text: "Mi trabajo me exige atender situaciones de violencia" },
  { id: 69, text: "Comunican tarde los asuntos de trabajo" },
  { id: 70, text: "Dificultan el logro de los resultados del trabajo" },
  { id: 71, text: "Cooperan poco cuando se necesita" },
  { id: 72, text: "Ignoran las sugerencias para mejorar su trabajo" }
];
