// frontend/src/utils/questions.js

export const QUESTIONS_GUIA_I = [
  // Sección I: Acontecimiento
  { id: 1, text: "¿Ha presenciado o sufrido algún accidente grave que le causara lesiones?" },
  { id: 2, text: "¿Ha presenciado o sufrido asaltos con violencia?" },
  { id: 3, text: "¿Ha presenciado o sufrido secuestros?" },
  { id: 4, text: "¿Ha presenciado o sufrido amenazas de muerte o daño físico?" },
  { id: 5, text: "¿Ha presenciado o sufrido la muerte violenta de algún compañero de trabajo o familiar?" },
  { id: 6, text: "¿Ha presenciado o sufrido algún otro acontecimiento que pusiera en peligro su vida?" },
  // Sección II: Recuerdos
  { id: 7, text: "¿Ha tenido recuerdos persistentes sobre el acontecimiento que le provocan malestar?" },
  { id: 8, text: "¿Ha tenido pesadillas o sueños recurrentes relacionados con el acontecimiento?" },
  // Sección III: Evitación
  { id: 9, text: "¿Ha tratado de evitar pensar, hablar o sentir acerca del acontecimiento?" },
  { id: 10, text: "¿Ha evitado actividades, lugares o personas que le recuerdan el acontecimiento?" },
  { id: 11, text: "¿Ha tenido dificultad para recordar partes importantes del acontecimiento?" },
  { id: 12, text: "¿Ha perdido el interés en realizar actividades que antes disfrutaba?" },
  { id: 13, text: "¿Se ha sentido distanciado o alejado de los demás?" },
  { id: 14, text: "¿Ha tenido dificultad para expresar sus sentimientos?" },
  { id: 15, text: "¿Ha sentido que su futuro se ha visto afectado o limitado?" },
  // Sección IV: Afectación
  { id: 16, text: "¿Ha tenido dificultad para dormir o se ha despertado frecuentemente?" },
  { id: 17, text: "¿Se ha sentido irritable o ha tenido arranques de coraje sin motivo?" },
  { id: 18, text: "¿Ha tenido dificultad para concentrarse en su trabajo o tareas?" },
  { id: 19, text: "¿Se ha sentido constantemente alerta o sobresaltado?" },
  { id: 20, text: "¿Se ha sobresaltado o asustado ante ruidos fuertes o inesperados?" }
];

export const QUESTIONS_GUIA_II = [
  { id: 1, text: "Mi trabajo me exige hacer mucho esfuerzo físico." },
  { id: 2, text: "Preocupación por sufrir un accidente laboral." },
  { id: 3, text: "Considero que las condiciones de mi lugar de trabajo son peligrosas o inseguras." },
  { id: 4, text: "Mi trabajo requiere que esté muy concentrado." },
  { id: 5, text: "Mi trabajo requiere que tome decisiones de forma rápida." },
  { id: 6, text: "Tengo que atender llamadas o correos fuera de mi horario laboral." },
  { id: 7, text: "Mi trabajo me exige hacer frente a situaciones emocionalmente difíciles." },
  { id: 8, text: "Mi trabajo me exige atender a personas con conductas difíciles." },
  { id: 9, text: "El volumen de trabajo que realizo es excesivo para mi horario." },
  { id: 10, text: "Mi trabajo me exige tomar decisiones con alto nivel de responsabilidad." },
  { id: 11, text: "Siento que tengo que tomar decisiones sin contar con la información necesaria." },
  { id: 12, text: "Recibo instrucciones contradictorias o inconsistentes de mis jefes." },
  { id: 13, text: "Tengo que realizar tareas que considero innecesarias o sin valor." },
  { id: 14, text: "Trabajo más de las horas establecidas en mi contrato de trabajo." },
  { id: 15, text: "Tengo que trabajar en días de descanso o días festivos." },
  { id: 16, text: "Mi trabajo interfiere con mis responsabilidades familiares o personales." },
  { id: 17, text: "Tengo que descuidar a mi familia por cumplir con mis tareas de trabajo." },
  { id: 18, text: "Mi jefe me permite decidir cómo realizar mis actividades diarias." },
  { id: 19, text: "Puedo decidir el ritmo y la velocidad a la que realizo mis tareas." },
  { id: 20, text: "Mi trabajo me permite adquirir nuevos conocimientos y habilidades." },
  { id: 21, text: "Puedo tomar descansos breves cuando lo considero necesario." },
  { id: 22, text: "Mi trabajo me ofrece oportunidades de desarrollo y crecimiento." },
  { id: 23, text: "Mi jefe inmediato escucha mis opiniones e ideas sobre el trabajo." },
  { id: 24, text: "Mi jefe inmediato me brinda apoyo para resolver problemas laborales." },
  { id: 25, text: "Mi jefe inmediato reconoce cuando realizo un buen trabajo." },
  { id: 26, text: "Recibo capacitación constante para realizar mis actividades de forma segura." },
  { id: 27, text: "Considero que la capacitación que recibo es de utilidad para mi trabajo." },
  { id: 28, text: "Las órdenes e instrucciones de mi jefe inmediato son claras." },
  { id: 29, text: "Mi jefe inmediato me trata con respeto y amabilidad." },
  { id: 30, text: "Mis compañeros de trabajo me apoyan cuando tengo dificultades laborales." },
  { id: 31, text: "Puedo expresar mis opiniones a mis compañeros sin temor a ser juzgado." },
  { id: 32, text: "Existe una relación de confianza y compañerismo en mi equipo de trabajo." },
  { id: 33, text: "En mi lugar de trabajo se fomentan las relaciones cordiales y el respeto mutuo." },
  { id: 34, text: "He presenciado agresiones físicas o verbales entre compañeros en mi trabajo." },
  { id: 35, text: "Me he sentido ignorado o excluido por mis compañeros de trabajo." },
  { id: 36, text: "He recibido críticas destructivas o burlas en mi centro de trabajo." },
  { id: 37, text: "En mi trabajo se cometen actos de hostigamiento o acoso psicológico." },
  { id: 38, text: "He recibido malos tratos de parte de mis superiores o jefes." },
  { id: 39, text: "Me bloquean o impiden las oportunidades que tengo para obtener ascensos." },
  { id: 40, text: "He presenciado actos de violencia física o verbal en mi centro laboral." },
  { id: 41, text: "Mi trabajo me exige un esfuerzo mental constante que me agota." },
  { id: 42, text: "Al finalizar mi jornada de trabajo, me siento exhausto físicamente." },
  { id: 43, text: "Siento que el estrés de mi trabajo está afectando mi salud personal." },
  { id: 44, text: "Tengo dificultades para relacionarme de forma cordial con mis compañeros." },
  { id: 45, text: "En mi área de trabajo se presentan conflictos constantes entre el personal." },
  { id: 46, text: "Siento que las relaciones con mis compañeros son tensas o distantes." }
];

export const QUESTIONS_GUIA_III = [
  // Group 1: Ambiente (1-5)
  { id: 1, text: "El espacio donde trabajo me permite realizar mis actividades de manera segura e higiénica." },
  { id: 2, text: "Mi lugar de trabajo tiene condiciones deficientes de luz, ventilación o temperatura." },
  { id: 3, text: "Considero que las condiciones de mi lugar de trabajo son peligrosas o insalubres." },
  { id: 4, text: "Las herramientas y equipos de trabajo que me proporcionan están en buen estado." },
  { id: 5, text: "Mi trabajo me exige realizar actividades peligrosas que ponen en riesgo mi salud." },
  // Group 2: Carga de trabajo (6-16)
  { id: 6, text: "Mi trabajo me exige hacer un esfuerzo físico que me agota." },
  { id: 7, text: "El ritmo al que debo realizar mi trabajo es demasiado acelerado." },
  { id: 8, text: "Mi trabajo requiere que esté concentrado por periodos de tiempo muy largos." },
  { id: 9, text: "Tengo que realizar tareas que me resultan emocionalmente difíciles." },
  { id: 10, text: "Las actividades que realizo requieren un alto esfuerzo mental de mi parte." },
  { id: 11, text: "El volumen de trabajo que realizo es excesivo para mi jornada laboral." },
  { id: 12, text: "Mi trabajo me exige tomar decisiones con un alto nivel de responsabilidad." },
  { id: 13, text: "En mi trabajo debo atender situaciones de emergencia o imprevistos de forma constante." },
  { id: 14, text: "Tengo que realizar tareas que considero innecesarias o sin valor práctico." },
  { id: 15, text: "Mi trabajo me exige resolver problemas complejos de forma rápida." },
  { id: 16, text: "Siento que el nivel de responsabilidad de mi trabajo excede mi capacidad." },
  // Group 3: Jornada (17-18)
  { id: 17, text: "Trabajo más horas de las establecidas en mi contrato de trabajo." },
  { id: 18, text: "Tengo que trabajar en mis días de descanso o fines de semana." },
  // Group 4: Interferencia (19-22)
  { id: 19, text: "Mi trabajo interfiere con mis responsabilidades familiares o personales." },
  { id: 20, text: "Tengo que descuidar mis actividades familiares por cumplir con las de mi trabajo." },
  { id: 21, text: "El tiempo que paso en el trabajo afecta mis relaciones familiares o sociales." },
  { id: 22, text: "Tengo que atender llamadas o correos de trabajo durante mis vacaciones." },
  // Group 5: Control (23-30)
  { id: 23, text: "Mi jefe me permite decidir cómo distribuir mis tiempos y actividades de trabajo." },
  { id: 24, text: "Puedo decidir el orden en que realizo mis tareas diarias." },
  { id: 25, text: "Mi trabajo me permite adquirir nuevos conocimientos y habilidades prácticas." },
  { id: 26, text: "Puedo tomar descansos breves cuando me siento cansado o tenso." },
  { id: 27, text: "Mi trabajo me ofrece oportunidades de desarrollo profesional a largo plazo." },
  { id: 28, text: "Considero que tengo control sobre las decisiones de mi área de trabajo." },
  { id: 29, text: "Puedo proponer cambios en la forma de realizar mis actividades cotidianas." },
  { id: 30, text: "Mi trabajo me da la libertad de aplicar mis propias ideas y soluciones." },
  // Group 6: Liderazgo (31-41)
  { id: 31, text: "Las órdenes e instrucciones de mi jefe inmediato son claras y precisas." },
  { id: 32, text: "Mi jefe inmediato me brinda apoyo para resolver problemas laborales." },
  { id: 33, text: "Mi jefe inmediato escucha mis opiniones sobre el trabajo." },
  { id: 34, text: "Mi jefe inmediato me trata con respeto y amabilidad en todo momento." },
  { id: 35, text: "Recibo capacitación constante sobre cómo realizar mi trabajo de forma segura." },
  { id: 36, text: "Considero que la capacitación que recibo es útil y de calidad." },
  { id: 37, text: "Mi jefe inmediato reconoce cuando realizo un buen trabajo o esfuerzo." },
  { id: 38, text: "Las decisiones que toma mi jefe inmediato son justas y transparentes." },
  { id: 39, text: "Mi jefe inmediato evalúa mi desempeño laboral de manera objetiva." },
  { id: 40, text: "Mi jefe inmediato fomenta el trabajo en equipo y la colaboración activa." },
  { id: 41, text: "Mi jefe inmediato me proporciona retroalimentación constructiva sobre mi trabajo." },
  // Group 7: Relaciones (42-46)
  { id: 42, text: "Mis compañeros de trabajo me apoyan cuando tengo exceso de tareas." },
  { id: 43, text: "Puedo expresar mis opiniones a mis compañeros sin temor a ser criticado." },
  { id: 44, text: "Existe una relación de confianza y compañerismo en mi equipo." },
  { id: 45, text: "En mi área de trabajo se fomentan las relaciones cordiales y el respeto mutuo." },
  { id: 46, text: "Siento que las relaciones con mis compañeros son tensas o distantes." },
  // Group 8: Reconocimiento (47-52)
  { id: 47, text: "Siento que mi esfuerzo en el trabajo es valorado por la empresa." },
  { id: 48, text: "El sueldo que recibo es justo para las actividades que realizo." },
  { id: 49, text: "La empresa ofrece incentivos o reconocimientos al buen desempeño." },
  { id: 50, text: "Tengo estabilidad laboral y seguridad de conservar mi empleo." },
  { id: 51, text: "La empresa me ofrece oportunidades claras de ascenso o promoción." },
  { id: 52, text: "Siento orgullo de pertenecer a esta empresa y realizar mi trabajo." },
  // Group 9: Pertenencia e Inestabilidad (53-56)
  { id: 53, text: "Me siento parte activa del equipo de trabajo de mi área." },
  { id: 54, text: "La empresa me informa sobre los planes de crecimiento o cambios organizacionales." },
  { id: 55, text: "Tengo claridad sobre los objetivos y metas de mi puesto." },
  { id: 56, text: "Considero que la carga de trabajo está distribuida de manera equitativa." },
  // Group 10: Violencia (57-64)
  { id: 57, text: "He recibido agresiones verbales o gritos de parte de mis superiores." },
  { id: 58, text: "He presenciado agresiones verbales o físicas entre compañeros en el trabajo." },
  { id: 59, text: "Me he sentido ignorado o excluido de las actividades de mi área." },
  { id: 60, text: "He recibido críticas destructivas o burlas recurrentes de mis compañeros." },
  { id: 61, text: "En mi lugar de trabajo se cometen actos de hostigamiento o acoso laboral." },
  { id: 62, text: "He recibido malos tratos o insultos de parte de mis superiores." },
  { id: 63, text: "He presenciado burlas o discriminación hacia otros compañeros." },
  { id: 64, text: "Me he sentido presionado o amenazado en mi estabilidad laboral sin justificación." },
  // Group 11: Supervisor / Subordinados specific (65-72)
  { id: 65, text: "Mi trabajo me exige atender clientes o usuarios muy molestos." },
  { id: 66, text: "Mi trabajo me exige atender personas en situación de crisis o enfermas." },
  { id: 67, text: "Para realizar mi trabajo debo fingir o demostrar emociones distintas a las mías." },
  { id: 68, text: "Mi trabajo me exige atender situaciones de violencia o delincuencia." },
  { id: 69, text: "Mis subordinados me reportan a tiempo las incidencias o problemas del trabajo." },
  { id: 70, text: "Siento que mis subordinados cooperan activamente para lograr los objetivos." },
  { id: 71, text: "Mis subordinados siguen las instrucciones que les proporciono de forma correcta." },
  { id: 72, text: "Mis subordinados demuestran respeto hacia mi puesto y liderazgo." }
];
